OSIS-6074 : Show classes in teaching charges
uclouvain/osis-portal pull request #2403
Opened 2021-09-08 10:59 UTC by BenJneB

Référence Jira : OSIS-

Vérifier les points suivants : 
- [ ] Ouvrir une release task Jira si le ticket génère une tâche pour la release : 
    - modification de configuration
    - table à synchroniser en entier, etc.
- [ ] Uniformiser les modèles osis avec les changements effectués dans osis-portal si nécessaire
- [ ] Permissions et droits d’accès mettre à jour la documentation si : 
    - on rajoute/modifie une permission
    - on rajoute/modifie un groupe d’utilisateurs, etc.

2021-09-08 11:02 UTC, chfivet requested changes

2021-09-08 11:02 UTC, chfivet commented on attribution/templates/tutor_charge_content.html
> +{% endblock %}
endline manquante

2021-09-08 11:02 UTC, chfivet commented on attribution/templates/tutor_charge_content.html
> +{% endblock %}
endline manquante

2021-09-08 12:18 UTC, mathieuzen approved these changes

2021-09-09 12:55 UTC, chfivet approved these changes

2021-09-09 12:55 UTC, merged