[WIP] OSIS-6110 : Use API and class-based-view to get list of programs
uclouvain/osis-portal pull request #2429
Opened 2021-09-15 15:22 UTC by BenJneB

Référence Jira : OSIS-

Vérifier les points suivants : 
- [ ] Ouvrir une release task Jira si le ticket génère une tâche pour la release : 
    - modification de configuration
    - table à synchroniser en entier, etc.
- [ ] Uniformiser les modèles osis avec les changements effectués dans osis-portal si nécessaire
- [ ] Permissions et droits d’accès mettre à jour la documentation si : 
    - on rajoute/modifie une permission
    - on rajoute/modifie un groupe d’utilisateurs, etc.

2021-09-15 17:24 UTC, BenJneB commented on performance/views/performance_home.py
> +    raise_exception = False
permission_required = base.is_faculty_administrator

2021-09-16 11:05 UTC, edd19 requested changes

2021-09-16 11:05 UTC, edd19 commented on performance/views/performance_home.py
> +              has_student and not _can_visualize_student_programs(self.request, self.student.registration_id))
Retirer les print

2021-09-16 11:05 UTC, edd19 commented on performance/views/performance_home.py
> +            print("YOLOOO", student_business.find_by_user_and_discriminate(self.request.user))
Retirer le print

2021-09-16 11:25 UTC, edd19 approved these changes

2021-09-16 11:26 UTC, mathieuzen requested changes

2021-09-16 11:26 UTC, mathieuzen commented on frontoffice/settings/osis_sdk/offer_enrollment.py
> +    Return SDK configuration of learning unit
le commentaire est pour learning_unit

2021-09-16 11:26 UTC, mathieuzen commented on performance/views/main.py
> +#     return layout.render(request, "performance_home_student.html", data)
why ?

2021-09-16 11:26 UTC, mathieuzen commented on performance/views/main.py
> +#     return layout.render(request, "admin/performance_home_admin.html", data)
?

2021-09-16 11:26 UTC, mathieuzen commented on performance/views/main.py
> +#     return d
?

2021-09-16 11:27 UTC, BenJneB commented on performance/views/main.py
> +#     return layout.render(request, "performance_home_student.html", data)
tout ca est a supprimer apres refactoring

2021-09-16 11:47 UTC, mathieuzen approved these changes

2021-09-16 12:06 UTC, merged