OSIS-6076 add class repartition students list url
uclouvain/osis-portal pull request #2435
Opened 2021-09-16 14:58 UTC by mathieuzen

Référence Jira : OSIS-

Vérifier les points suivants : 
- [ ] Ouvrir une release task Jira si le ticket génère une tâche pour la release : 
    - modification de configuration
    - table à synchroniser en entier, etc.
- [ ] Uniformiser les modèles osis avec les changements effectués dans osis-portal si nécessaire
- [ ] Permissions et droits d’accès mettre à jour la documentation si : 
    - on rajoute/modifie une permission
    - on rajoute/modifie un groupe d’utilisateurs, etc.

2021-09-17 12:42 UTC, albrugnetti requested changes

2021-09-17 12:42 UTC, albrugnetti commented on attribution/services/learning_unit.py
> +                learning_unit_title = api_instance.learningunitstitle_read(year=int(year), acronym=acronym)['title']
Remove cast to int because method signature force to int

2021-09-17 12:42 UTC, albrugnetti commented on attribution/services/learning_unit.py
> +                effective_classes = api_instance.get_learning_unit_classes(year=int(year), acronym=acronym)
Remove cast to int because method signature force to int

2021-09-17 12:42 UTC, albrugnetti commented on attribution/urls.py
> +        url(r'^$', StudentsListView.as_view(), name='attribution_students'),
student_enrollments_by_learning_unit

2021-09-17 12:42 UTC, albrugnetti commented on attribution/urls.py
> +        url(r'^(?P<class_code>[0-9A-Za-z-]{1})$', StudentsListView.as_view(), name='attribution_class_students')
student_enrollments_by_learning_class

2021-09-17 12:42 UTC, albrugnetti commented on attribution/urls.py
> +    ),
Move xls export view inside "**students/(?P<learning_unit_acronym>[0-9A-Za-z-]+)/(?P<learning_unit_year>[0-9]+)/**"

2021-09-17 12:42 UTC, albrugnetti commented on attribution/views/students_list.py
> +        return LearningUnitService.get_learning_unit_title(
peux-tu spliter en deux sous fonction :

```python
def learning_unit_title(self):
     return self._get_learning_class_title() if 'class_code' in self.kwargs else self.get_learning_unit_title()

def _get_learning_unit_title(self):
      return  LearningUnitService.get_learning_unit_title(XXX)

def _get_learning_class_title(self):
      classes = LearningUnitService.get_effective_classes(
                acronym=self.kwargs['learning_unit_acronym'],
                year=self.kwargs['learning_unit_year'],
                person=self.request.user.person
            )
      return next( (effective_class.title_fr for effective_class in classes if effective_class.code == self.kwargs['class_code']), '')

2021-09-20 12:48 UTC, BenJneB approved these changes

2021-09-20 13:52 UTC, albrugnetti approved these changes

2021-09-20 13:53 UTC, merged