OSIS-6123 : ExamEnrollmentForm + Check
uclouvain/osis-portal pull request #2441
Opened 2021-09-20 16:17 UTC by BenJneB

Référence Jira : OSIS-

Vérifier les points suivants : 
- [ ] Ouvrir une release task Jira si le ticket génère une tâche pour la release : 
    - modification de configuration
    - table à synchroniser en entier, etc.
- [ ] Uniformiser les modèles osis avec les changements effectués dans osis-portal si nécessaire
- [ ] Permissions et droits d’accès mettre à jour la documentation si : 
    - on rajoute/modifie une permission
    - on rajoute/modifie un groupe d’utilisateurs, etc.

2021-09-20 17:38 UTC, BenJneB commented on exam_enrollment/services/learning_unit_enrollment.py
> +        return enrollments
renvoit la liste des étudiants attribués à une UE
Besoin : liste des UE auxquelles un étudiant est inscrit (pour un programme & une année)

2021-09-20 17:38 UTC, BenJneB commented on exam_enrollment/services/trainings.py
> +        return title
inutilisé

2021-09-20 17:40 UTC, BenJneB commented on exam_enrollment/tests/views/test_check_form.py
> +class ExamEnrollmentFormTest(TestCase):
remove useless

2021-09-21 08:09 UTC, mathieuzen requested changes

2021-09-21 08:09 UTC, mathieuzen commented on exam_enrollment/views/enrollment_form.py
> +        etat_to_inscr = None if not etat_to_inscr or etat_to_inscr == 'None' else etat_to_inscr
== 'None' ??

2021-09-21 08:34 UTC, mathieuzen approved these changes

2021-09-21 08:35 UTC, merged