[WIP] OSIS-5753 : Discriminate osis side
uclouvain/osis-portal pull request #2534
Opened 2021-10-28 14:13 UTC by BenJneB

Référence Jira : OSIS-

Vérifier les points suivants : 
- [ ] Ouvrir une release task Jira si le ticket génère une tâche pour la release : 
    - modification de configuration
    - table à synchroniser en entier, etc.
- [ ] Uniformiser les modèles osis avec les changements effectués dans osis-portal si nécessaire
- [ ] Permissions et droits d’accès mettre à jour la documentation si : 
    - on rajoute/modifie une permission
    - on rajoute/modifie un groupe d’utilisateurs, etc.

2021-11-08 15:03 UTC, mathieuzen requested changes

2021-11-08 15:33 UTC, BenJneB commented on base/services/offer_enrollment.py
> +                global_id=global_id,
Cela peut être un administrateur qui veux voir les offerenrollment d'un student.

2021-11-09 08:59 UTC, mathieuzen commented on base/services/offer_enrollment.py
> +                global_id=global_id,
bien vu

2021-11-09 08:59 UTC, mathieuzen approved these changes

2021-11-09 14:59 UTC, merged