OSIS-6214 : Suppression de l'utilisation de learningUnitYear dans lis…
uclouvain/osis-portal pull request #2549
Opened 2021-11-05 10:40 UTC by verpoorten

…t.py

Référence Jira : OSIS-

Vérifier les points suivants : 
- [ ] Ouvrir une release task Jira si le ticket génère une tâche pour la release : 
    - modification de configuration
    - table à synchroniser en entier, etc.
- [ ] Uniformiser les modèles osis avec les changements effectués dans osis-portal si nécessaire
- [ ] Permissions et droits d’accès mettre à jour la documentation si : 
    - on rajoute/modifie une permission
    - on rajoute/modifie un groupe d’utilisateurs, etc.

2021-11-08 09:43 UTC, basmot requested changes

2021-11-08 09:43 UTC, basmot commented on base/migrations/0088_delete_learningunityear.py
> +    ]
N'oublie pas de le faire pour LearningUnit également

2021-11-08 10:50 UTC, verpoorten commented
rerun unit tests

2021-11-08 11:15 UTC, verpoorten commented
rerun unit tests

2021-11-08 11:58 UTC, verpoorten commented
rerun unit tests

2021-11-08 12:08 UTC, verpoorten commented
rerun unit tests

2021-11-12 08:08 UTC, albrugnetti commented
rerun unit tests

2021-11-12 08:08 UTC, albrugnetti commented
Problème de migration Internship réglé dans https://github.com/uclouvain/osis-portal-internship/commit/d24502e1c6b01b3be0da8a707a4acc1f3c0f4772

2021-11-12 08:16 UTC, merged