Osis 6232 add attendance mark link in dashboard
uclouvain/osis-portal pull request #2673
Opened 2022-02-16 13:04 UTC by edd19

Référence Jira : OSIS-

Vérifier les points suivants : 
- [ ] Ouvrir une release task Jira si le ticket génère une tâche pour la release : 
    - modification de configuration
    - table à synchroniser en entier, etc.
- [ ] Uniformiser les modèles osis avec les changements effectués dans osis-portal si nécessaire
- [ ] Permissions et droits d’accès mettre à jour la documentation si : 
    - on rajoute/modifie une permission
    - on rajoute/modifie un groupe d’utilisateurs, etc.

2022-02-16 14:47 UTC, basmot requested changes

2022-02-16 14:47 UTC, basmot commented on assessments/calendar/attendance_mark_calendar.py
> +        return events_filtered[0] if events_filtered else None
Cela ne devrait pas se trouver dans https://github.com/uclouvain/osis-portal/blob/dev/assessments/services/assessments.py ?

2022-02-16 14:47 UTC, basmot commented on assessments/views/attendance_mark/offers.py
> +        }
Tests unitaires sur view ? (Juste un permission et assertTemplateUsed ?)

2022-02-16 14:47 UTC, basmot commented on assessments/views/attendance_mark/outside_period.py
> +        }
Tests unitaires sur view ? (Juste un permission et assertTemplateUsed ?)

2022-02-17 09:08 UTC, edd19 commented
rerun unit tests

2022-02-18 08:37 UTC, merged