Install osis-notification widget
uclouvain/osis-portal pull request #2729
Opened 2022-04-28 10:34 UTC by SebCorbin

2022-04-28 11:32 UTC, edd19 requested changes

2022-04-28 11:32 UTC, edd19 commented on base/templates/layout.html
> +    <link rel="stylesheet" href="{% static 'osis_notification/osis-notification.css' %}" />
Il faut aussi ajouter une condition dépendant de si osis_notification est installé ou non

2022-04-28 11:32 UTC, edd19 commented on base/templates/layout.html
> +    <script type="text/javascript" src="{% static 'osis_notification/osis-notification.umd.min.js' %}"></script>
Même remarque ici

2022-04-28 11:33 UTC, BenJneB commented on base/templates/layout.html
> +    <script type="text/javascript" src="{% static 'osis_notification/osis-notification.umd.min.js' %}"></script>
Il faut peut-être faire la même chose côté OSIS.

2022-04-29 13:57 UTC, BenJneB approved these changes

2022-04-29 14:02 UTC, merged