Osis 7355
uclouvain/osis-portal pull request #2833
Opened 2022-11-04 07:13 UTC by edd19

Référence Jira : OSIS-

Vérifier les points suivants : 
- [ ] Ouvrir une release task Jira si le ticket génère une tâche pour la release : 
    - modification de configuration
    - table à synchroniser en entier, etc.
- [ ] Uniformiser les modèles osis avec les changements effectués dans osis-portal si nécessaire
- [ ] Permissions et droits d’accès mettre à jour la documentation si : 
    - on rajoute/modifie une permission
    - on rajoute/modifie un groupe d’utilisateurs, etc.

2022-11-08 12:35 UTC, edd19 commented
rerun quality checks

2022-11-08 12:35 UTC, edd19 commented
rerun unit tests

2022-11-08 15:05 UTC, basmot requested changes

2022-11-08 15:05 UTC, basmot commented on inscription_aux_cours/services/formulaire_inscription.py
> +        return _formulaire_api_call(person, "get_formulaire", annee=annee, sigle_formation=sigle_formation,)
ça m'étonne de passer l'année... on peut proposer un formulaire pour l'étudiant sur une année précédente ou future ? :-O

2022-11-09 08:54 UTC, edd19 commented on inscription_aux_cours/services/formulaire_inscription.py
> +        return _formulaire_api_call(person, "get_formulaire", annee=annee, sigle_formation=sigle_formation,)
Non on ne peut pas.
L'année est là pour le profil de l'étudiant. Pour rechercher le profil de l'étudiant on a besoin de savoir le sigle de la formation, son noma ainsi que l'année.
C'est via se profil qu'on va alors dès lors pouvoir savoir si l'inscription est ouverte ou non.
Par contre je me suis rendu compte que je devais renforcer le service de lecture de formulaire pour bloquer si l'inscription est fermée.

2022-11-09 11:38 UTC, basmot commented on inscription_aux_cours/services/formulaire_inscription.py
> +        return _formulaire_api_call(person, "get_formulaire", annee=annee, sigle_formation=sigle_formation,)
Ok donc ça serait le rôle du client de dire "je vuex m'inscrire paux cours pour l'année X" ? Il me semble que c'est plutôt le système qui devrait alculer automatiquement la bonne année ?

2022-11-22 10:38 UTC, basmot requested changes

2022-11-22 13:58 UTC, edd19 commented on learning_unit/views/autocomplete.py
> +        return ClasseService().rechercher_classes(self.person, annee=self.annee, code=self.code)
J'ai voulu créer un service à minima mais oui je peux faire dans un deuxième temps une api qui retourne tout les types (ue et classe)

2022-11-23 08:42 UTC, basmot approved these changes

2022-11-23 11:20 UTC, merged