OSIS-8113 preserve form input values after page is reloaded with errors
uclouvain/osis-portal pull request #3022
Opened 2023-06-12 14:13 UTC by mathieuzen

Référence Jira : OSIS-8113

Vérifier les points suivants : 
- [ ] Ouvrir une release task Jira si le ticket génère une tâche pour la release : 
    - modification de configuration
    - table à synchroniser en entier, etc.
- [ ] Uniformiser les modèles osis avec les changements effectués dans osis-portal si nécessaire
- [ ] Permissions et droits d’accès mettre à jour la documentation si : 
    - on rajoute/modifie une permission
    - on rajoute/modifie un groupe d’utilisateurs, etc.

2023-06-12 14:50 UTC, basmot requested changes

2023-06-12 14:50 UTC, basmot commented on inscription_aux_cours/templates/inscription_aux_cours/cours/formulaire.html
> +    document.querySelector('#id_demande_particuliere').addEventListener('input', (e) => {
Je ferais une `const id_demande_particuliere`

2023-06-12 14:50 UTC, basmot commented on inscription_aux_cours/templates/inscription_aux_cours/cours/formulaire.html
> +        debounce_save_id = setTimeout(() => localStorage.setItem('demande_particuliere', e.target.value), DEBOUNCE_DELAY);
Je ferais une `const demande_particuliere`.
Pareil pour demandes_cours_hors_formulaire et demande_particuliere.

2023-06-12 14:50 UTC, basmot commented on inscription_aux_cours/templates/inscription_aux_cours/cours/formulaire.html
> +        });
Par rapport au autocomplete, il y a dedans uniquement les codes UE ; mais il faut stocker également le choix du contexte (le radio bouton au-dessus).

2023-06-14 09:01 UTC, mathieuzen commented on inscription_aux_cours/templates/inscription_aux_cours/cours/formulaire.html
> +        debounce_save_id = setTimeout(() => localStorage.setItem('demande_particuliere', e.target.value), DEBOUNCE_DELAY);
ici la demande particulière est la valeur du champ texte, pas besoin de split si ?

2023-06-14 09:32 UTC, basmot requested changes

2023-06-14 09:32 UTC, basmot commented on inscription_aux_cours/templates/inscription_aux_cours/cours/formulaire.html
> +        serializedValues.split(separateurDemandes).forEach((code) => {
Je renomemrais code en serializedValue

2023-06-14 11:21 UTC, basmot approved these changes

2023-06-14 11:21 UTC, merged