OSIS-7652: [CAS ACCESS]En tant qu'étudiant, je désire accéder au menu de gestion des inscriptions aux examens pour m'inscrire aux examens
uclouvain/osis-portal pull request #3269
Opened 2023-12-11 11:55 UTC by jervandeputt

Référence Jira : OSIS-

Vérifier les points suivants : 
- [ ] Ouvrir une release task Jira si le ticket génère une tâche pour la release : 
    - modification de configuration
    - table à synchroniser en entier, etc.
- [ ] Uniformiser les modèles osis avec les changements effectués dans osis-portal si nécessaire
- [ ] Permissions et droits d’accès mettre à jour la documentation si : 
    - on rajoute/modifie une permission
    - on rajoute/modifie un groupe d’utilisateurs, etc.

2024-01-04 13:54 UTC, johangirardin commented on inscription_evaluation/locale/en/LC_MESSAGES/django.po
> +msgstr ""
Click on the course code (acronym) for which you wish to register for assessments => bien que j'ai toujours un doute si on utilise evaluation ou assesment dans osis...

2024-01-04 14:04 UTC, jervandeputt commented on inscription_evaluation/locale/en/LC_MESSAGES/django.po
> +msgstr ""
Pour le début de la phrase, c'est la même que dans inscription aux cours (qui a été faite par le traducteur).
Quant à "evaluation", Claire m'a dit de pas perdre de temps sur l'anglais, un traducteur va repasser à la fin des développements et on devra modifier avant de mettre en prod. Et comme j'ai mis "evaluation partout, je propose de garder en l'état pour l'instant

2024-01-04 14:04 UTC, johangirardin commented on inscription_evaluation/locale/en/LC_MESSAGES/django.po
> +"You can modify your evaluation entries as long as you have not submitted."
You can modify your evaluation entries as long as you have not submitted them.

2024-01-04 14:14 UTC, johangirardin commented on inscription_evaluation/locale/fr_BE/LC_MESSAGES/django.po
> +
Vous pouvez modifier vos inscriptions aux évaluations tant que vous n'avez pas soumis le formulaire. OU ...tant que vous ne les avez pas soumises

2024-01-04 14:28 UTC, jervandeputt commented on inscription_evaluation/locale/fr_BE/LC_MESSAGES/django.po
> +
C'était indiqué comme j''ai mis dans le mockup

2024-01-04 14:39 UTC, johangirardin commented on inscription_evaluation/templates/inscription_evaluation/blocks/legende.html
> +                        <td>Réinsc</td>
Faut tt de m prévoir les traductions pour les abréviations non?

2024-01-04 14:39 UTC, johangirardin commented on inscription_evaluation/templates/inscription_evaluation/blocks/legende.html
> +                        <td>Créd.</td>
Idem

2024-01-04 14:58 UTC, johangirardin commented on inscription_evaluation/views/formulaire_inscription.py
> +        # return self.formulaire.session_de_travail
?

2024-01-04 15:03 UTC, jervandeputt commented on inscription_evaluation/templates/inscription_evaluation/blocks/legende.html
> +                        <td>Réinsc</td>
non c'est des mots en tant que tel (d'ailleurs c'est l'API qui les envoie) 
(Comme dans inscription aux cours)

2024-01-05 10:10 UTC, basmot requested changes

2024-01-05 10:10 UTC, basmot commented on inscription_evaluation/views/demande_inscription.py
> +class EnregistrerDemandeInscriptionView(LoginRequiredMixin, InscriptionEvaluationViewMixin, View):
Je ferais une seule view "FormulaireInscription" qui définit le GET et le POST => je déplacerais EnregistrerDemandeInscriptionView.post dans FormulaireInscriptionView. Cf. standard 'implémentation REST : ressource/ POST GET PUT DELETE => une URL qui possède un nom d'action n'est pas REST.

2024-01-05 10:10 UTC, basmot commented on inscription_evaluation/views/soumettre_demande_inscription.py
> +        return redirect('inscription-evaluation:selectionner-programme')
Soumettre la demande est une action qui modifie le système => ça ne peut aps être un GET ; ça doit être un POST. Aussi, pareil pour l'implémentation REST ; je passerais par Recapitulatif.post pour soumettre.

2024-01-08 08:36 UTC, jervandeputt commented on dashboard/views/home.py
> +                    has_perm=self.request.user.has_perm('base.is_student')
Non, une vérification est faite lorsque la méthode `is_available()` est appelée : 

```python
@property
    def is_available(self) -> bool:
        return self.has_perm and (self.app in settings.INSTALLED_APPS or self.url == settings.OSIS_SCORE_ENCODING_URL)
```

2024-01-08 14:15 UTC, basmot approved these changes

2024-01-08 14:17 UTC, jervandeputt commented
rerun unit tests

2024-01-08 14:47 UTC, jervandeputt commented
2 tests random KO

2024-01-08 14:47 UTC, merged