OSIS-8629-corrections: issues 9, 10 & 11
uclouvain/osis-portal pull request #3325
Opened 2024-02-19 16:01 UTC by jervandeputt

Référence Jira : OSIS-

Vérifier les points suivants : 
- [ ] Ouvrir une release task Jira si le ticket génère une tâche pour la release : 
    - modification de configuration
    - table à synchroniser en entier, etc.
- [ ] Uniformiser les modèles osis avec les changements effectués dans osis-portal si nécessaire
- [ ] Permissions et droits d’accès mettre à jour la documentation si : 
    - on rajoute/modifie une permission
    - on rajoute/modifie un groupe d’utilisateurs, etc.

2024-02-19 16:21 UTC, basmot requested changes

2024-02-19 16:21 UTC, basmot commented on inscription_evaluation/templatetags/affichage_note_justification.py
> +    }.get(note[:1], note)
Pourquoi ?

2024-02-19 16:57 UTC, basmot commented on inscription_evaluation/templatetags/affichage_note_justification.py
> +    }.get(note[:1], note)
Arf zut ... alors on devrait plutôt diviser la note finale en 2 champs "note" + "session" pour être propre, car cette solution là me semble risquée de vite ne plus fonctionner au moindre changement

2024-02-21 13:03 UTC, BenJneB approved these changes

2024-02-21 13:31 UTC, merged

2024-02-21 13:41 UTC, johangirardin approved these changes

2024-02-21 13:48 UTC, jervandeputt commented on inscription_evaluation/templates/inscription_evaluation/formulaire_inscription.html
> +                                        <td>{% if inscription.credite %}Créd.{% else %}-{% endif %}</td>
Non, comme dans inscription aux cours, c'est pas demandé