OSIS-9340: refactor permission + adaptation récupération PDF par uuid
uclouvain/osis-portal pull request #3447
Opened 2024-08-27 12:35 UTC by jervandeputt

Référence Jira : OSIS-

Vérifier les points suivants : 
- [ ] Ouvrir une release task Jira si le ticket génère une tâche pour la release : 
    - modification de configuration
    - table à synchroniser en entier, etc.
- [ ] Uniformiser les modèles osis avec les changements effectués dans osis-portal si nécessaire
- [ ] Permissions et droits d’accès mettre à jour la documentation si : 
    - on rajoute/modifie une permission
    - on rajoute/modifie un groupe d’utilisateurs, etc.

2024-08-27 13:01 UTC, jervandeputt commented
rerun unit tests

2024-08-27 13:08 UTC, jervandeputt commented
test KO osis-common

2024-08-27 14:12 UTC, basmot requested changes

2024-08-27 14:12 UTC, basmot commented on inscription_aux_cours/services/pdf_pae_valide_jury.py
>          )
Tu peux la déprécier ?

2024-08-27 14:12 UTC, basmot commented on inscription_aux_cours/services/pdf_proposition_pae.py
>          )
pareil ?

2024-08-28 09:53 UTC, basmot approved these changes

2024-08-28 09:53 UTC, merged